// Standalone receipt HTML: escape all donor/provider text and embed the official logo.
type Gift={id:string;status:string;amount:number|string;donation_type:string;payment_method:string;transaction_id?:string;completed_at?:string;created_at:string;donor_name?:string;donor_email?:string};
export type ReceiptChurch={name:string;assembly:string;address?:string;contacts?:string;email?:string};
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]!));
export function buildDonationReceipt(gift:Gift,church:ReceiptChurch,logo:string,testMode:boolean){
 if(gift.status!=='completed')throw new Error('Only confirmed gifts can receive a receipt.');
 const amount=Number(gift.amount);if(!Number.isFinite(amount)||amount<=0)throw new Error('Invalid receipt amount.');
 if(!/^data:image\/png;base64,[A-Za-z0-9+/=]+$/.test(logo))throw new Error('The church logo could not be loaded.');
 const date=new Date(gift.completed_at||gift.created_at);if(!Number.isFinite(date.getTime()))throw new Error('Invalid receipt date.');
 const giving=({tithe:'Tithe',general:'General Offering',offering:'Special Offering',campaign:'Campaign Gift'} as Record<string,string>)[gift.donation_type]||gift.donation_type;
 const row=(label:string,value:unknown)=>`<div class="row"><dt>${escape(label)}</dt><dd>${escape(value||'—')}</dd></div>`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${testMode?'Test ':''}Donation Receipt — ${escape(gift.id)}</title><style>
 *{box-sizing:border-box}body{margin:0;background:#edf1f4;color:#153549;font-family:Arial,Helvetica,sans-serif;font-size:14px;line-height:1.6}.toolbar{max-width:820px;margin:22px auto;display:flex;align-items:center;justify-content:space-between;gap:16px;padding:0 20px}.toolbar span{color:#526777;font-size:13px}button{background:#153549;color:white;border:0;border-radius:8px;padding:12px 18px;cursor:pointer;font-weight:700}.paper{max-width:780px;margin:0 auto 40px;background:white;box-shadow:0 12px 50px #15354912;border-top:7px solid #bd9a55;padding:42px 48px}.brand{display:flex;gap:20px;align-items:center;padding-bottom:28px;border-bottom:1px solid #e2e8ea}.brand img{width:112px;height:90px;object-fit:contain}.brand h1{font-size:21px;line-height:1.3;letter-spacing:.2px;margin:0 0 6px}.assembly{color:#a17b38;font-size:14px;font-weight:700}.contact{font-size:12px;color:#627583;white-space:pre-line;margin-top:8px}.heading{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin:32px 0 24px}.heading h2{margin:3px 0 4px;font-size:30px;line-height:1.2}.eyebrow{font-size:10px;letter-spacing:2px;color:#8a7450;font-weight:700}.badge{color:#176448;background:#e9f6ee;border:1px solid #d0e9dc;border-radius:18px;padding:6px 13px;font-size:11px;font-weight:700}.test{padding:12px 16px;background:#fff6de;border:1px solid #ead5a3;border-radius:8px;color:#7f5d1a;font-size:12px;margin-bottom:22px}.total{display:flex;justify-content:space-between;align-items:center;gap:20px;background:#f0f6f5;border:1px solid #dce8e4;padding:23px 25px;border-radius:12px;margin-bottom:26px}.total span{font-size:12px;color:#5a7474}.total strong{font-size:31px;color:#165848;letter-spacing:-.5px}.total small{font-size:12px;letter-spacing:1px}dl{margin:0}.row{display:grid;grid-template-columns:155px 1fr;gap:20px;padding:12px 0;border-bottom:1px solid #edf0f2;break-inside:avoid}.row dt{font-size:12px;color:#6e7e88}.row dd{margin:0;font-weight:600;overflow-wrap:anywhere}.thanks{margin:28px 0 0;padding:20px 22px;border-left:3px solid #bd9a55;background:#fbfaf7;font-size:13px;color:#546b77}.thanks strong{display:block;color:#163e51;margin-bottom:5px}.footer{margin-top:28px;padding-top:18px;border-top:1px solid #e2e8ea;color:#798893;font-size:10px;line-height:1.7}.footer p{margin:4px 0}.print-help{font-size:11px;margin-top:8px;color:#6e7e88}@page{size:A4;margin:16mm}@media print{body{background:white}.toolbar,.print-help{display:none}.paper{max-width:none;margin:0;padding:22px 20px;box-shadow:none}.heading,.total,.thanks,.brand{break-inside:avoid}}@media(max-width:600px){.paper{padding:26px 20px;margin:0 12px 24px}.brand{align-items:flex-start;gap:12px}.brand img{width:70px;height:64px}.brand h1{font-size:17px}.heading h2{font-size:25px}.heading{gap:12px}.row{grid-template-columns:100px 1fr;gap:12px}.total{padding:18px}.total strong{font-size:26px}.toolbar{flex-wrap:wrap}}
 </style></head><body><div class="toolbar"><span>Your ${testMode?'test ':''}donation receipt</span><button type="button" onclick="window.print()">Print / Save as PDF</button></div><main class="paper"><header class="brand"><img src="${logo}" alt="Church logo"><div><h1>${escape(church.name)}</h1><div class="assembly">${escape(church.assembly)}</div>${church.address?`<div class="contact">${escape(church.address)}</div>`:''}${church.contacts?`<div class="contact">Tel: ${escape(church.contacts)}</div>`:''}${church.email?`<div class="contact">Email: ${escape(church.email)}</div>`:''}</div></header><div class="heading"><div><span class="eyebrow">GIVING WITH PURPOSE</span><h2>${testMode?'Test Donation Receipt':'Donation Receipt'}</h2></div><span class="badge">✓ ${testMode?'TEST CONFIRMED':'CONFIRMED'}</span></div>${testMode?'<div class="test"><strong>SANDBOX / TEST MODE</strong> · No real money was collected. This is a test receipt, not proof of a real donation or a tax receipt.</div>':''}<section class="total"><div><span>Gift amount</span><br><strong>$${amount.toFixed(2)}</strong> <small>USD</small></div><span>${escape(giving)}</span></section><dl>${row('Receipt reference',gift.id)}${row('Confirmed date',date.toLocaleString('en-US',{dateStyle:'long',timeStyle:'short',timeZone:'UTC'})+' UTC')}${row('Donor',gift.donor_name||'Anonymous')}${gift.donor_email?row('Donor email',gift.donor_email):''}${row('Giving type',giving)}${row('Payment method',gift.payment_method)}${row('Payment reference',gift.transaction_id)}</dl><div class="thanks"><strong>Thank you for your generosity.</strong>Your giving supports the work and mission of ${escape(church.name)}. We appreciate your faithful support.</div><footer class="footer"><p>Issued through House of Ezra Giving · ${escape(church.assembly)}</p><p>${testMode?'For testing only.':'Payment acknowledgment only. This document makes no claim about tax deductibility.'}</p></footer><p class="print-help">Use Print / Save as PDF above to keep a PDF copy.</p></main></body></html>`;
}
export async function downloadDonationReceipt(gift:Gift,church:ReceiptChurch,testMode:boolean){
 const response=await fetch('/branding/house-of-ezra-logo-transparent.png');if(!response.ok)throw new Error('Could not load the church logo. Please try downloading again.');
 const blob=await response.blob();
 const logo=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Could not read the church logo.'));reader.readAsDataURL(new Blob([blob],{type:'image/png'}));});
 const html=buildDonationReceipt(gift,church,logo,testMode);
 const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));
 const anchor=document.createElement('a');anchor.href=url;anchor.download=`Ezracash-${testMode?'Test-':''}Receipt-${String(gift.id).replace(/[^a-zA-Z0-9-]/g,'')}.html`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),10000);
}
