"use client";
import { useEffect,useState } from 'react';
export default function MonthlyConfirmation(){
  const [token,setToken]=useState(''),[record,setRecord]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const value=window.location.hash.slice(1);if(value){setToken(value);window.history.replaceState(null,'',window.location.pathname);sessionStorage.setItem('ezra-monthly-confirmation',value);}else setToken(sessionStorage.getItem('ezra-monthly-confirmation')||'');},[]);
  useEffect(()=>{if(!token)return;let stopped=false,attempts=0,timer:ReturnType<typeof setTimeout>;const load=async()=>{try{const response=await fetch('/api/payments/stripe/subscription-status',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const data=await response.json();if(stopped)return;if(!response.ok)throw new Error(data.error);setRecord(data);setError('');if(data.first_payment_confirmed)return;}catch(e){if(!stopped)setError(e instanceof Error?e.message:'Could not verify monthly giving.');}if(!stopped&&++attempts<20)timer=setTimeout(load,3000);};void load();return()=>{stopped=true;clearTimeout(timer);};},[token]);
  async function manage(){setBusy(true);try{const response=await fetch('/api/payments/stripe/portal',{method:'POST',headers:{Authorization:`Bearer ${token}`}});const data=await response.json();if(!response.ok)throw new Error(data.error);if(!data.url?.startsWith('https://billing.stripe.com/'))throw new Error('Invalid portal destination.');window.location.assign(data.url);}catch(e){setError(e instanceof Error?e.message:'Could not open portal.');setBusy(false);}}
  const login=process.env.NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL_URL;
  return <main style={{minHeight:'100vh',background:'#f2f6f9',padding:'64px 20px',fontFamily:'Arial,sans-serif',color:'#193b55'}}><section style={{maxWidth:560,margin:'0 auto',background:'white',borderRadius:24,padding:32,boxShadow:'0 15px 50px #173e5512'}}><small>HOUSE OF EZRA · MONTHLY GIVING</small><h1>{record?.first_payment_confirmed?'Thank you for your monthly gift':'Confirming monthly giving'}</h1><p style={{lineHeight:1.7}}>{record?.first_payment_confirmed?`Your first gift is recorded. Your agreed donation is $${Number(record.amount).toFixed(2)} USD each month until canceled.`:'We are waiting for Stripe to confirm your subscription and first payment. Please do not subscribe again.'}</p>{record&&<p>Subscription status: <strong>{record.status}</strong></p>}{error&&<p role="alert">{error}</p>}{token&&<button disabled={busy} onClick={manage} style={{width:'100%',padding:16,border:0,borderRadius:12,background:'#dbb04c',color:'#193b55',fontWeight:700,cursor:'pointer'}}>{busy?'Opening portal…':'Manage or cancel my monthly giving'}</button>}{login?.startsWith('https://billing.stripe.com/')&&<p><a href={login}>Access subscription portal using my email</a></p>}<p><a href="/">Return to House of Ezra Giving</a></p></section></main>;
}
