"use client";
import { useEffect, useMemo, useState } from "react";
import { Activity, BarChart3, Camera, CheckCircle2, CircleDollarSign, Edit3, Eye, FileUp, HeartHandshake, LogOut, Plus, RefreshCw, Save, ShieldCheck, Target, UserCircle, Users, WalletCards, X } from "lucide-react";

import WorkspaceActions from "../WorkspaceActions";

type Campaign={id:string;title:string;category:string;description:string;goal:number;amount:number;image:string;status:string};
type Donation={id:string;campaign_id:string|null;donation_type:string;donor_name:string;donor_email?:string|null;amount:number;payment_method:string;transaction_id?:string|null;status:string;created_at:string;campaign_title?:string|null};
type Expense={id:string;category:string;description:string;amount:number;payment_method:string;reference?:string|null;status:string;expense_date:string;created_at:string;has_receipt?:boolean};
type Profile={id:string;email:string;display_name:string;phone:string;ministry_role:string};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(Number(n)||0);
const tabs=[{id:"dashboard",label:"Overview",icon:BarChart3},{id:"fundraising",label:"Fundraising",icon:Target},{id:"donations",label:"Donations",icon:CircleDollarSign},{id:"donors",label:"Donors",icon:Users},{id:"expenses",label:"Expenses",icon:WalletCards},{id:"profile",label:"My Profile",icon:UserCircle}];
const emptyCampaign={title:"",category:"GENERAL",description:"",goal:"",image:"",status:"active"};
const emptyDonation={campaign_id:"",donor_name:"Anonymous",donor_email:"",amount:"",payment_method:"Manual",donation_type:"general",transaction_id:"",status:"completed"};
const emptyExpense={category:"Ministry",description:"",amount:"",payment_method:"Bank Transfer",reference:"",status:"recorded",expense_date:"",receipt:null as File|null};

export default function StaffDashboard(){
 const [loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[tab,setTab]=useState("dashboard"),[error,setError]=useState(""),[toast,setToast]=useState("");
 const [campaigns,setCampaigns]=useState<Campaign[]>([]),[donations,setDonations]=useState<Donation[]>([]),[expenses,setExpenses]=useState<Expense[]>([]),[profile,setProfile]=useState<Profile|null>(null);
 const [modal,setModal]=useState<"campaign"|"donation"|"expense"|"profile"|null>(null),[saving,setSaving]=useState(false);
 const [campaignForm,setCampaignForm]=useState<any>(emptyCampaign),[editingCampaign,setEditingCampaign]=useState<string|null>(null),[donationForm,setDonationForm]=useState<any>(emptyDonation),[expenseForm,setExpenseForm]=useState<any>(emptyExpense),[profileForm,setProfileForm]=useState<any>({display_name:"",email:"",phone:"",ministry_role:"Staff"});
 const load=async(silent=false)=>{if(silent)setRefreshing(true);else setLoading(true);setError("");try{const [c,d,e,p]=await Promise.all([fetch("/api/campaigns?admin=1",{cache:"no-store"}),fetch("/api/donations",{cache:"no-store"}),fetch("/api/admin/expenses",{cache:"no-store"}),fetch("/api/admin/profile",{cache:"no-store"})]);if([c,d,e,p].some(r=>r.status===401)){location.href="/admin";return;}const [cj,dj,ej,pj]=await Promise.all([c.json(),d.json(),e.json(),p.json()]);if(c.ok)setCampaigns(Array.isArray(cj)?cj:[]);if(d.ok)setDonations(Array.isArray(dj)?dj:[]);if(e.ok)setExpenses(Array.isArray(ej)?ej:[]);if(p.ok){setProfile(pj);setProfileForm({display_name:pj.display_name||"",email:pj.email||"",phone:pj.phone||"",ministry_role:pj.ministry_role||"Staff"});}const problems=[!c.ok?cj.error:null,!d.ok?dj.error:null,!e.ok?ej.error:null,!p.ok?pj.error:null].filter(Boolean);if(problems.length)setError(problems.join(" · "));}catch(e:any){setError(e?.message||"Could not load Staff workspace.")}finally{setLoading(false);setRefreshing(false)}};
 async function audit(action:string,details=""){try{await fetch("/api/admin/audit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,details})})}catch{}}
 useEffect(()=>{const selected=new URLSearchParams(window.location.search).get("view");if(tabs.some(t=>t.id===selected))setTab(selected!);load();},[]);useEffect(()=>{if(!loading)void audit(`staff_view_${tab}`,`Staff opened ${tab}`)},[tab,loading]);
 const completed=useMemo(()=>donations.filter(d=>d.status==="completed"),[donations]);const total=completed.reduce((s,d)=>s+Number(d.amount),0);const active=campaigns.filter(c=>c.status==="active").length;const donorCount=new Set(completed.map(d=>(d.donor_email||d.donor_name||"Anonymous").toLowerCase())).size;
 function selectPage(id:string){setTab(id);window.history.replaceState({},"",`${window.location.pathname}?view=${id}`);window.scrollTo({top:0,behavior:"smooth"});}
 function openCreate(type:"campaign"|"donation"|"expense"){setError("");setEditingCampaign(null);setModal(type);if(type==="campaign")setCampaignForm({...emptyCampaign});if(type==="donation")setDonationForm({...emptyDonation});if(type==="expense")setExpenseForm({...emptyExpense});void audit(`staff_open_${type}_form`,`Staff opened ${type} creation form`)}
 function openProfile(){setProfileForm({display_name:profile?.display_name||"",email:profile?.email||"",phone:profile?.phone||"",ministry_role:profile?.ministry_role||"Staff"});setModal("profile");}
 async function saveCampaign(e:React.FormEvent){e.preventDefault();setSaving(true);try{const payload=editingCampaign?{...campaignForm,action:"update",id:editingCampaign}:campaignForm;const r=await fetch("/api/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not save campaign.");setToast(editingCampaign?"Campaign updated on the public site.":"Campaign published to the public site.");setModal(null);await load(true);await audit(editingCampaign?"campaign_updated":"campaign_created",`${j.id||editingCampaign||""} · ${campaignForm.title}`)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 function editCampaign(c:Campaign){setEditingCampaign(c.id);setCampaignForm({title:c.title,category:c.category,description:c.description,goal:String(c.goal),image:c.image||"",status:c.status});setError("");setModal("campaign");void audit("staff_edit_campaign",`${c.id} · ${c.title}`)}
 async function archiveCampaign(c:Campaign){if(!window.confirm(`Archive “${c.title}”? It will no longer be presented as an active campaign.`))return;setSaving(true);try{const r=await fetch("/api/campaigns",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"archive",id:c.id})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not archive campaign.");setToast("Campaign archived.");await load(true);await audit("campaign_archived",`${c.id} · ${c.title}`)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function saveDonation(e:React.FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch("/api/donations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(donationForm)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not record donation.");setToast("Donation recorded successfully.");setModal(null);await load(true);await audit("donation_recorded",`${j.id||""} · ${donationForm.donor_name} · ${donationForm.amount}`)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function saveExpense(e:React.FormEvent){e.preventDefault();setSaving(true);try{
  const fd=new FormData();Object.entries(expenseForm).forEach(([key,value])=>{if(key!=="receipt"&&value!==null&&value!==undefined)fd.append(key,String(value));});if(expenseForm.receipt)fd.append("receipt",expenseForm.receipt);
  const r=await fetch("/api/admin/expenses",{method:"POST",body:fd});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not record expense.");setToast(expenseForm.receipt?"Expense saved with receipt attached.":"Expense recorded successfully.");setModal(null);await load(true);await audit("expense_recorded",`${j.id||""} · ${expenseForm.description} · ${expenseForm.amount}`)
}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function saveProfile(e:React.FormEvent){e.preventDefault();setSaving(true);try{const r=await fetch("/api/admin/profile",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(profileForm)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not update profile.");setToast("Profile updated successfully.");setModal(null);await load(true);await audit("staff_profile_updated",`Staff updated own profile`)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 async function logout(){await audit("staff_logout","Staff signed out");await fetch("/api/auth/logout",{method:"POST"});location.href="/admin"}
 if(loading)return <main className="staff-page"><div className="staff-loading"><div className="staff-loading-mark"><HeartHandshake size={28}/></div><strong>Preparing Staff Workspace</strong><span>Loading ministry operations securely…</span><div className="staff-loading-line"><i/></div></div></main>;
 return <main className="staff-page"><div className="staff-wrap">
  <header className="staff-top"><div className="staff-brand"><div className="staff-mark"><HeartHandshake size={22}/></div><div><span>HOUSE OF EZRA GIVING</span><h1>{tabs.find(t=>t.id===tab)?.label === "Overview" ? "Ministry operations" : tabs.find(t=>t.id===tab)?.label}</h1><p>Staff workspace / {tabs.find(t=>t.id===tab)?.label}</p></div></div><div className="staff-head-actions"><span className="staff-role"><ShieldCheck size={13}/> Staff access</span><button className="staff-signout" onClick={logout}><LogOut size={15}/> Sign out</button></div></header>
  {error&&<div className="staff-error"><span>{error}</span><button onClick={()=>setError("")}><X size={14}/></button></div>}
  {toast&&<div className="staff-toast"><CheckCircle2 size={17}/><span>{toast}</span><button onClick={()=>setToast("")}><X size={14}/></button></div>}
  <aside className="workspace-sidebar staff-sidebar"><a className="workspace-brand" href="/admin/staff/dashboard"><img src="/branding/house-of-ezra-logo-transparent.png" alt="House of Ezra"/><span>HOUSE OF EZRA<small>STAFF WORKSPACE</small></span></a><p className="workspace-nav-label">MINISTRY OPERATIONS</p>  <nav className="staff-nav" aria-label="Staff workspace navigation">{tabs.map(({id,label,icon:Icon})=><button key={id} aria-pressed={tab===id} className={tab===id?"active":""} onClick={()=>{selectPage(id)}}><Icon size={15}/><span>{label}</span></button>)}</nav><div className="workspace-side-footer"><a href="/" target="_blank" rel="noreferrer">View giving site →</a><button onClick={logout}><LogOut size={17}/>Sign out</button></div></aside>
  {tab==="dashboard"&&<section className="staff-hero"><div><span>STAFF OPERATIONS · {profile?.ministry_role||"MINISTRY"}</span><h2>Small acts.<br/>Extraordinary impact.</h2><p>Manage campaigns, record gifts and keep ministry expenses organised from one clear workspace.</p></div><div className="staff-hero-actions"><button onClick={()=>openCreate("campaign")}><Plus size={15}/> New campaign</button><button className="ghost" onClick={()=>load(true)}><RefreshCw size={15} className={refreshing?"staff-spin":""}/> Refresh</button></div></section>}
  <section className="staff-stats"><div><CircleDollarSign size={18}/><small>Total completed giving</small><strong>{money(total)}</strong></div><div><Target size={18}/><small>Active campaigns</small><strong>{active}</strong></div><div><Users size={18}/><small>Unique donors</small><strong>{donorCount}</strong></div><div><Activity size={18}/><small>Records</small><strong>{donations.length+expenses.length}</strong></div></section>
  {tab==="dashboard"&&<WorkspaceActions onSelect={selectPage} staff/>}
  {tab==="dashboard"&&<Overview donations={completed.slice(0,8)} campaigns={campaigns} money={money} selectTab={selectPage} onNewDonation={()=>openCreate("donation")} onNewExpense={()=>openCreate("expense")}/>}
  {tab==="fundraising"&&<Campaigns campaigns={campaigns} money={money} onNew={()=>openCreate("campaign")} onEdit={editCampaign} onArchive={archiveCampaign} />}
  {tab==="donations"&&<Donations donations={donations} money={money} onNew={()=>openCreate("donation")} />}
  {tab==="donors"&&<DonorList donations={completed} money={money}/>}
  {tab==="expenses"&&<Expenses expenses={expenses} money={money} onNew={()=>openCreate("expense")}/>}
  {tab==="profile"&&<ProfileCard profile={profile} onEdit={openProfile}/>}
  <section className="staff-security"><ShieldCheck size={21}/><div><strong>Private accountability is active</strong><p>Staff changes can appear on the public giving experience where applicable, while the identity of the staff member and activity trail remain private to authorized administrators and the System Developer.</p></div></section>
 </div>
 {modal&&<Modal title={modal==="campaign"?"Create fundraising campaign":modal==="donation"?"Record donation":modal==="expense"?"Record ministry expense":"Update my profile"} onClose={()=>{if(!saving)setModal(null)}}>
  {modal==="campaign"&&<form className="staff-form" onSubmit={saveCampaign}><Field label="Campaign title"><input required value={campaignForm.title} onChange={e=>setCampaignForm({...campaignForm,title:e.target.value})}/></Field><div className="staff-form-grid"><Field label="Category"><input value={campaignForm.category} onChange={e=>setCampaignForm({...campaignForm,category:e.target.value})}/></Field><Field label="Goal"><input required type="number" min="1" step="0.01" value={campaignForm.goal} onChange={e=>setCampaignForm({...campaignForm,goal:e.target.value})}/></Field></div><Field label="Description"><textarea value={campaignForm.description} onChange={e=>setCampaignForm({...campaignForm,description:e.target.value})}/></Field><Field label="Image URL (optional)"><input value={campaignForm.image} onChange={e=>setCampaignForm({...campaignForm,image:e.target.value})}/></Field><Actions saving={saving}/></form>}
  {modal==="donation"&&<form className="staff-form" onSubmit={saveDonation}><div className="staff-form-grid"><Field label="Donor name"><input required value={donationForm.donor_name} onChange={e=>setDonationForm({...donationForm,donor_name:e.target.value})}/></Field><Field label="Email"><input type="email" value={donationForm.donor_email} onChange={e=>setDonationForm({...donationForm,donor_email:e.target.value})}/></Field></div><div className="staff-form-grid"><Field label="Amount"><input required type="number" min="0.01" step="0.01" value={donationForm.amount} onChange={e=>setDonationForm({...donationForm,amount:e.target.value})}/></Field><Field label="Campaign"><select value={donationForm.campaign_id} onChange={e=>setDonationForm({...donationForm,campaign_id:e.target.value})}><option value="">General giving</option>{campaigns.filter(c=>c.status!=="archived").map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></Field></div><div className="staff-form-grid"><Field label="Giving type"><select value={donationForm.donation_type} onChange={e=>setDonationForm({...donationForm,donation_type:e.target.value})}><option value="general">General</option><option value="tithe">Tithe</option><option value="offering">Offering</option><option value="campaign">Campaign</option></select></Field><Field label="Payment method"><input value={donationForm.payment_method} onChange={e=>setDonationForm({...donationForm,payment_method:e.target.value})}/></Field></div><Field label="Transaction reference"><input value={donationForm.transaction_id} onChange={e=>setDonationForm({...donationForm,transaction_id:e.target.value})}/></Field><Actions saving={saving}/></form>}
  {modal==="expense"&&<form className="staff-form" onSubmit={saveExpense}><div className="staff-form-grid"><Field label="Category"><input value={expenseForm.category} onChange={e=>setExpenseForm({...expenseForm,category:e.target.value})}/></Field><Field label="Amount"><input required type="number" min="0.01" step="0.01" value={expenseForm.amount} onChange={e=>setExpenseForm({...expenseForm,amount:e.target.value})}/></Field></div><Field label="Description"><textarea required value={expenseForm.description} onChange={e=>setExpenseForm({...expenseForm,description:e.target.value})}/></Field><div className="staff-form-grid"><Field label="Payment method"><input value={expenseForm.payment_method} onChange={e=>setExpenseForm({...expenseForm,payment_method:e.target.value})}/></Field><Field label="Reference"><input value={expenseForm.reference} onChange={e=>setExpenseForm({...expenseForm,reference:e.target.value})}/></Field></div><div className="staff-receipt-upload"><div className="staff-receipt-head"><div><strong>Supporting receipt</strong><span>PDF/photo upload or camera capture · max 4 MB</span></div>{expenseForm.receipt&&<b>{expenseForm.receipt.name}</b>}</div><div className="staff-receipt-actions"><label><FileUp size={15}/><span>Upload PDF/photo</span><input type="file" accept="application/pdf,image/*" onChange={e=>setExpenseForm({...expenseForm,receipt:e.target.files?.[0]||null})}/></label><label><Camera size={15}/><span>Take photo</span><input type="file" accept="image/*" capture="environment" onChange={e=>setExpenseForm({...expenseForm,receipt:e.target.files?.[0]||null})}/></label>{expenseForm.receipt&&<button type="button" onClick={()=>setExpenseForm({...expenseForm,receipt:null})}>Remove</button>}</div></div><Field label="Date"><input type="date" value={expenseForm.expense_date} onChange={e=>setExpenseForm({...expenseForm,expense_date:e.target.value})}/></Field><Actions saving={saving}/></form>}
  {modal==="profile"&&<form className="staff-form" onSubmit={saveProfile}><Field label="Display name"><input required value={profileForm.display_name} onChange={e=>setProfileForm({...profileForm,display_name:e.target.value})}/></Field><Field label="Email"><input required type="email" value={profileForm.email} onChange={e=>setProfileForm({...profileForm,email:e.target.value})}/></Field><div className="staff-form-grid"><Field label="Phone"><input value={profileForm.phone} onChange={e=>setProfileForm({...profileForm,phone:e.target.value})}/></Field><Field label="Ministry role"><input value={profileForm.ministry_role} onChange={e=>setProfileForm({...profileForm,ministry_role:e.target.value})}/></Field></div><Actions saving={saving}/></form>}
 </Modal>}
 </main>;
}
function Actions({saving}:{saving:boolean}){return <div className="staff-form-actions"><button className="staff-save" disabled={saving}>{saving?<RefreshCw size={14} className="staff-spin"/>:<Save size={14}/>} {saving?"Saving…":"Save changes"}</button></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="staff-field"><span>{label}</span>{children}</label>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="staff-modal-overlay" onMouseDown={e=>{if(e.currentTarget===e.target)onClose()}}><section className="staff-modal"><header><div><span>STAFF ACTION</span><h3>{title}</h3></div><button onClick={onClose}><X size={18}/></button></header>{children}</section></div>}
function Overview({donations,campaigns,money,selectTab,onNewDonation,onNewExpense}:{donations:Donation[];campaigns:Campaign[];money:(n:number)=>string;selectTab:(id:string)=>void;onNewDonation:()=>void;onNewExpense:()=>void}){return <section className="staff-content"><div className="staff-section-head"><div><span>WORKSPACE OVERVIEW</span><h2>Today at a glance</h2></div><div className="staff-inline-actions"><button onClick={onNewDonation}><Plus size={14}/> Record gift</button><button onClick={onNewExpense}><Plus size={14}/> Add expense</button></div></div><div className="staff-panels"><div className="staff-panel"><div className="staff-panel-head"><div><span>RECENT GIVING</span><h3>Latest donations</h3></div><button onClick={()=>selectTab("donations")}>View all</button></div>{donations.length?<div className="staff-list">{donations.slice(0,6).map(d=><div className="staff-list-row" key={d.id}><div className="staff-avatar">{(d.donor_name||"A").slice(0,1).toUpperCase()}</div><div><strong>{d.donor_name||"Anonymous"}</strong><span>{d.campaign_title||"General giving"} · {new Date(d.created_at).toLocaleDateString()}</span></div><b>{money(d.amount)}</b></div>)}</div>:<Empty text="No completed donations yet."/>}</div><div className="staff-panel"><div className="staff-panel-head"><div><span>CAMPAIGNS</span><h3>Active fundraising</h3></div><button onClick={()=>selectTab("fundraising")}>Manage</button></div>{campaigns.filter(c=>c.status==="active").slice(0,5).map(c=><div className="campaign-row" key={c.id}><div><strong>{c.title}</strong><span>{c.category}</span></div><div><b>{money(c.amount)}</b><small>of {money(c.goal)}</small></div></div>)}{campaigns.filter(c=>c.status==="active").length===0&&<Empty text="No active campaigns."/>}</div></div></section>}
function Campaigns({campaigns,money,onNew,onEdit,onArchive}:{campaigns:Campaign[];money:(n:number)=>string;onNew:()=>void;onEdit:(c:Campaign)=>void;onArchive:(c:Campaign)=>void}){return <section className="staff-content"><div className="staff-section-head"><div><span>FUNDRAISING</span><h2>Campaign portfolio</h2><p>Changes made here are reflected in the public campaign experience.</p></div><button className="staff-action-primary" onClick={onNew}><Plus size={14}/> New campaign</button></div><div className="staff-card-grid">{campaigns.map(c=>{const pct=Math.min(100,Number(c.amount)/Math.max(Number(c.goal),1)*100);return <article className="staff-data-card" key={c.id}>{c.image&&<img className="workspace-campaign-image" src={c.image} alt="" loading="lazy"/>}<div className="staff-data-top"><span>{c.status}</span><small>{c.category}</small></div><h3>{c.title}</h3><p>{c.description||"No campaign description available."}</p><div className="staff-progress"><i style={{width:`${pct}%`}}/></div><div className="staff-data-bottom"><b>{money(c.amount)}</b><span>{Math.round(pct)}% of {money(c.goal)}</span></div><div className="staff-card-actions"><button onClick={()=>onEdit(c)}><Edit3 size={12}/> Edit</button>{c.status!=="archived"&&<button onClick={()=>onArchive(c)}><Eye size={12}/> Archive</button>}</div></article>})}</div>{!campaigns.length&&<Empty text="No campaigns available."/>}</section>}
function Donations({donations,money,onNew}:{donations:Donation[];money:(n:number)=>string;onNew:()=>void}){return <section className="staff-content"><div className="staff-section-head"><div><span>GIVING RECORDS</span><h2>Donation activity</h2></div><button className="staff-action-primary" onClick={onNew}><Plus size={14}/> Record donation</button></div><div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Donor</th><th>Type</th><th>Campaign</th><th>Method</th><th>Date</th><th>Amount</th></tr></thead><tbody>{donations.map(d=><tr key={d.id}><td><strong>{d.donor_name||"Anonymous"}</strong><small>{d.donor_email||""}</small></td><td>{d.donation_type}</td><td>{d.campaign_title||"General"}</td><td>{d.payment_method}</td><td>{new Date(d.created_at).toLocaleDateString()}</td><td><b>{money(d.amount)}</b></td></tr>)}</tbody></table>{!donations.length&&<Empty text="No donation records available."/>}</div></section>}
function DonorList({donations,money}:{donations:Donation[];money:(n:number)=>string}){const map=new Map<string,{name:string;email:string;total:number;count:number;last:string}>();donations.forEach(d=>{const k=(d.donor_email||d.donor_name||"Anonymous").toLowerCase();const old=map.get(k);if(old){old.total+=Number(d.amount);old.count++;if(new Date(d.created_at)>new Date(old.last))old.last=d.created_at}else map.set(k,{name:d.donor_name||"Anonymous",email:d.donor_email||"",total:Number(d.amount),count:1,last:d.created_at})});return <section className="staff-content"><div className="staff-section-head"><div><span>DONOR DIRECTORY</span><h2>Supporter relationships</h2></div></div><div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Donor</th><th>Gifts</th><th>Total giving</th><th>Last gift</th></tr></thead><tbody>{Array.from(map.values()).map(d=><tr key={d.email||d.name}><td><strong>{d.name}</strong><small>{d.email}</small></td><td>{d.count}</td><td><b>{money(d.total)}</b></td><td>{new Date(d.last).toLocaleDateString()}</td></tr>)}</tbody></table>{!map.size&&<Empty text="No donor records yet."/>}</div></section>}
function Expenses({expenses,money,onNew}:{expenses:Expense[];money:(n:number)=>string;onNew:()=>void}){return <section className="staff-content"><div className="staff-section-head"><div><span>OPERATIONS</span><h2>Expense ledger</h2></div><button className="staff-action-primary" onClick={onNew}><Plus size={14}/> Add expense</button></div><div className="staff-table-wrap"><table className="staff-table"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Method</th><th>Receipt</th><th>Status</th><th>Amount</th></tr></thead><tbody>{expenses.map(e=><tr key={e.id}><td>{new Date(e.expense_date).toLocaleDateString()}</td><td><strong>{e.description}</strong><small>{e.reference||"No reference"}</small></td><td>{e.category}</td><td>{e.payment_method}</td><td>{e.has_receipt?<a href={`/api/admin/expense-receipts/${e.id}`} target="_blank" rel="noreferrer">View</a>:"—"}</td><td>{e.status}</td><td><b>-{money(e.amount)}</b></td></tr>)}</tbody></table>{!expenses.length&&<Empty text="No expense records yet."/>}</div></section>}
function ProfileCard({profile,onEdit}:{profile:Profile|null;onEdit:()=>void}){return <section className="staff-content"><div className="staff-profile-card"><div className="staff-profile-avatar"><UserCircle size={34}/></div><div className="staff-profile-copy"><span>STAFF IDENTITY</span><h2>{profile?.display_name||"Staff account"}</h2><p>{profile?.email||""}</p><div><b>{profile?.ministry_role||"Staff"}</b><span>{profile?.phone||"No phone number"}</span></div></div><button className="staff-action-primary" onClick={onEdit}><Edit3 size={14}/> Edit profile</button></div></section>}
function Empty({text}:{text:string}){return <div className="staff-empty"><Eye size={18}/><strong>{text}</strong><span>Nothing to display right now.</span></div>}
