"use client";
import { useEffect,useMemo,useState } from "react";
import { Activity, ArrowRight, CheckCircle2, Clock3, Home, LockKeyhole, LogOut, MapPin, RefreshCw, Server, Settings, ShieldCheck, UserCog, Users } from "lucide-react";
type Audit={id:string;action:string;details:string;ip_address?:string;session_id?:string;created_at:string;email:string;role:string};
const actionLabel=(a:string)=>a.replace(/^view_staff_/,'Viewed staff · ').replaceAll('_',' ').replace(/\b\w/g,m=>m.toUpperCase());
export default function DeveloperDashboard(){
 const [loading,setLoading]=useState(true),[sessions,setSessions]=useState<any[]>([]),[audit,setAudit]=useState<Audit[]>([]),[sessionError,setSessionError]=useState("");
 async function loadSecurity(silent=false){if(!silent)setSessionError("");try{const r=await fetch("/api/admin/security",{cache:"no-store"});const j=await r.json();if(r.ok){setSessions(j.sessions||[]);setAudit(j.audit||[])}else setSessionError(j.error||"Could not load security activity.")}catch{setSessionError("Could not load security activity.")}finally{setLoading(false)}}
 async function logout(){await fetch("/api/auth/logout",{method:"POST"});window.location.href="/admin"}
 useEffect(()=>{const t=setTimeout(()=>loadSecurity(),650);const i=setInterval(()=>loadSecurity(true),15000);return()=>{clearTimeout(t);clearInterval(i)}},[]);
 const locationOf=(s:any)=>[s.city,s.region,s.country].filter(Boolean).join(", ")||"Location unavailable";
 const summaries=useMemo(()=>{const m=new Map<string,{email:string;role:string;actions:number;last:string;login:string;logout:boolean}>();audit.forEach(a=>{const k=a.session_id||a.email;const x=m.get(k)||{email:a.email,role:a.role,actions:0,last:a.created_at,login:"",logout:false};if(a.action!="login"&&a.action!="logout")x.actions++;if(a.action==="login")x.login=a.created_at;if(a.action==="logout")x.logout=true;if(new Date(a.created_at)>new Date(x.last))x.last=a.created_at;m.set(k,x)});return [...m.values()].slice(0,10)},[audit]);
 if(loading)return <main className="dev-page"><div className="dev-loading"><div className="dev-loading-mark"><ShieldCheck size={27}/></div><strong>Preparing Developer Workspace</strong><span>Securing your control center…</span><div className="dev-loading-line"><i/></div></div></main>;
 return <main className="dev-page"><div className="dev-wrap">
  <header className="dev-top"><div className="dev-brand"><div className="dev-logo"><ShieldCheck size={23}/></div><div><div className="dev-kicker">HOUSE OF EZRA · CONTROL PLANE</div><h1>Developer Workspace</h1><p>Technical governance, security and privileged access.</p></div></div><div className="dev-top-actions"><a className="dev-home" href="/admin/developer"><Home size={14}/> Dashboard</a><button className="dev-signout" onClick={logout}><LogOut size={14}/> Sign out</button></div></header>
  <section className="dev-hero"><div className="dev-hero-copy"><span>SYSTEM DEVELOPER</span><h2>Keep the giving platform secure, clear and accountable.</h2><p>A focused command center for people, sessions and the complete activity trail behind House of Ezra Giving.</p></div><div className="dev-shield"><ShieldCheck size={48}/></div></section>
  <section className="dev-metrics"><div className="dev-metric"><div className="dev-metric-icon"><ShieldCheck size={19}/></div><div><small>SECURITY STATUS</small><strong>Protected</strong></div></div><div className="dev-metric"><div className="dev-metric-icon"><Users size={19}/></div><div><small>ACCESS MODEL</small><strong>Role-based</strong></div></div><div className="dev-metric"><div className="dev-metric-icon"><Activity size={19}/></div><div><small>ACTIVE SESSIONS</small><strong>{sessions.length}</strong></div></div><div className="dev-metric"><div className="dev-metric-icon"><Clock3 size={19}/></div><div><small>AUDIT EVENTS</small><strong>{audit.length}</strong></div></div></section>
  <section className="dev-grid"><div className="dev-card"><div className="dev-card-head"><div><span>COMMAND CENTER</span><h3>Developer controls</h3></div><LockKeyhole size={19}/></div>
   <a className="dev-action" href="/admin/security"><div><div className="dev-action-icon"><ShieldCheck size={16}/></div><div><strong>Security Center</strong><small>Sessions, audit events and security controls</small></div></div><ArrowRight size={16}/></a>
   <a className="dev-action" href="/admin/staff?from=developer"><div><div className="dev-action-icon"><UserCog size={16}/></div><div><strong>User Management</strong><small>Review privileged accounts and role assignments</small></div></div><ArrowRight size={16}/></a>
   <a className="dev-action" href="/admin/administrator?from=developer"><div><div className="dev-action-icon"><Settings size={16}/></div><div><strong>Administration</strong><small>Fundraising, donations, expenses and settings</small></div></div><ArrowRight size={16}/></a>
  </div><div className="dev-card"><div className="dev-card-head"><div><span>LIVE ACCESS</span><h3>Active sessions</h3></div><button className="dev-refresh" onClick={()=>loadSecurity(true)}><RefreshCw size={15}/></button></div>{sessionError&&<p className="dev-session-error">{sessionError}</p>}<div className="dev-session-list">{sessions.slice(0,6).map(s=><div className="dev-session" key={s.id}><div className="dev-session-avatar"><Activity size={15}/></div><div className="dev-session-main"><strong>{s.display_name||s.email}</strong><span>{s.role} · {s.ip_address||"IP unavailable"}</span><small><MapPin size={11}/> {locationOf(s)}</small></div><i>Active</i></div>)}{!sessions.length&&<div className="dev-no-sessions">No active sessions.</div>}</div></div></section>
  <section className="dev-card dev-audit-card"><div className="dev-card-head"><div><span>ACCOUNTABILITY</span><h3>What each login did</h3><p className="dev-card-sub">A session-level summary of sign-ins and activity recorded across the system.</p></div><Server size={19}/></div><div className="dev-audit-summary">{summaries.map((s,i)=><div className="dev-audit-summary-row" key={`${s.email}-${i}`}><div className="dev-audit-user"><div className="dev-audit-avatar">{s.email.slice(0,1).toUpperCase()}</div><div><strong>{s.email}</strong><span>{s.role} · {s.actions} recorded action{s.actions===1?"":"s"}</span></div></div><div className="dev-audit-time"><small>Last activity</small><b>{new Date(s.last).toLocaleString()}</b></div><CheckCircle2 size={16}/></div>)}{!summaries.length&&<div className="dev-no-sessions">No activity has been recorded yet.</div>}</div><div className="dev-audit-feed"><div className="dev-feed-head"><span>RECENT ACTIVITY</span><a href="/admin/security">Open full audit trail <ArrowRight size={13}/></a></div>{audit.slice(0,12).map(a=><div className="dev-feed-row" key={a.id}><div className="dev-feed-dot"/><div><strong>{actionLabel(a.action)}</strong><span>{a.email} · {a.details||"System activity"}</span></div><time>{new Date(a.created_at).toLocaleString()}</time></div>)}</div></section>
  <section className="dev-card dev-governance"><div className="dev-card-head"><div><span>HEALTH & GOVERNANCE</span><h3>System boundaries</h3></div><Server size={19}/></div><div className="dev-boundary"><div><strong><CheckCircle2 size={13}/> Authentication</strong><p>All privileged users enter through the single /admin login and are routed by role.</p></div><div><strong><CheckCircle2 size={13}/> Separation of duties</strong><p>Administrator and Staff permissions remain separate from developer security controls.</p></div><div><strong><CheckCircle2 size={13}/> Auditability</strong><p>Login, logout, password, account, role and workspace actions can be reviewed by the Developer.</p></div><div><strong><CheckCircle2 size={13}/> Data layer</strong><p>Application records remain behind protected server-side API routes.</p></div></div></section>
 </div></main>;
}
